#StormPeak Network - Skyblock Server
online-mode=false
server-ip=159.69.187.179
server-port=25567
server-name=StormPeak Skyblock
motd=§6§lStormPeak §7§| §bSkyblock §7» §fplay.stormpeak.net
max-players=100
view-distance=10
simulation-distance=8
difficulty=normal
gamemode=0
force-gamemode=false
pvp=false
spawn-protection=0
allow-nether=true
allow-end=true
enable-command-block=true
white-list=false
level-name=world
level-type=flat
generate-structures=false
network-compression-threshold=256
