#StormPeak Network - Hub Server
online-mode=false
server-ip=159.69.187.179
server-port=25565
server-name=StormPeak Hub
motd=§6§lStormPeak Network §7§| §fHub§r §7» §aplay.stormpeak.net
max-players=100
view-distance=8
simulation-distance=6
difficulty=peaceful
gamemode=2
force-gamemode=true
pvp=false
spawn-protection=16
allow-nether=false
allow-end=false
enable-command-block=true
white-list=false
level-name=world_hub
level-type=flat
generate-structures=false
network-compression-threshold=256
player-idle-timeout=0
max-world-size=1000
online-mode=false
