#StormPeak Network - Survival Server
online-mode=false
server-ip=159.69.187.179
server-port=25566
server-name=StormPeak Survival
motd=§6§lStormPeak §7§| §aSurvival §7» §fplay.stormpeak.net
max-players=100
view-distance=10
simulation-distance=8
difficulty=normal
gamemode=0
force-gamemode=false
pvp=true
spawn-protection=16
allow-nether=true
allow-end=true
enable-command-block=true
white-list=false
level-name=world
level-type=default
generate-structures=true
network-compression-threshold=256
